name: CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Find npm Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.OS }}-npm-
      - name: Run npm
        run: npm install
      - name: Check ESLint
        run: npm run lint
      - name: Check code style
        run: npm run format:prettier
      - name: Check typescript
        run: npm run lint:types
      - name: Run unit test
        run: npm run test --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/**/*
          flags: unittests
