name: CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Find Yarn Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.OS }}-yarn-
      - name: Run yarn
        run: yarn
      - name: Check ESLint
        run: yarn lint
      - name: Check code style
        run: yarn format:prettier
      - name: Check typescript
        run: yarn lint:types
      - name: Run unit test
        run: yarn test --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/**/*
          flags: unittests
